name: Merge main branch to development branch
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  merge-main-to-development:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Git Config
        run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
      - name: Merge and push
        run: |
            git fetch --unshallow
            git checkout development
            git pull
            git merge main
            git push
