name: Merge main brach to development branch
on: 
  pull_request:
    branches: [main]

jobs:
  merge-main-to-development:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge main branch to development branch
      run: |
          git fetch --unshallow
          git checkout development
          git pull
          git merge --no-ff main
          git push
